web/models/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def init_app(app):
    print(app.config["SQLALCHEMY_DATABASE_URI"])
    db.init_app(app)
    with app.app_context():
        db.create_all()

web/models/folios.py
from . import db


class Folio(db.Model):
    id = db.Column(
        db.BigInteger().with_variant(db.Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )

    name = db.Column(db.String)
    email = db.Column(db.String)

    biography = db.Column(db.String)
    education = db.Column(db.String)

web/models/users.py
from flask_login import UserMixin
from . import db


class User(db.Model, UserMixin):
    id = db.Column(
        db.BigInteger().with_variant(db.Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )
    password = db.Column(db.String, unique=True, nullable=False)
    email = db.Column(db.String)

    first_name = db.Column(db.String)
    last_name = db.Column(db.String)

web/forms/accounts.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import validators


class LoginForm(FlaskForm):
    email = StringField(
        "name", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    password = StringField(
        "password",
        validators=[
            validators.DataRequired(),
            validators.Length(min=3, message="มากกว่า 3"),
        ],
    )


class RegisterForm(FlaskForm):
    email = StringField(
        "email", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    password = StringField(
        "password",
        validators=[
            validators.DataRequired(),
            validators.Length(min=3, message="มากกว่า 3"),
        ],
    )
    first_name = StringField("first_name", validators=[validators.DataRequired()])
    last_name = StringField("password", validators=[validators.DataRequired()])

web/forms/folios.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import validators
from wtforms import widgets


class FolioForm(FlaskForm):
    email = StringField(
        "email", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    name = StringField("Name", validators=[validators.DataRequired()])
    biography = StringField("Biography", widget=widgets.TextArea())
    education = StringField("Education", widget=widgets.TextArea())

web/main.py
from flask import Flask, render_template, redirect, url_for
from flask_login import LoginManager
from werkzeug.utils import secure_filename

from views import accounts
from views import folios
import models
from models import users

import os

login_manager = LoginManager()
login_manager.login_view = "accounts.login"


@login_manager.unauthorized_handler
def unauthorized():
    # do stuff
    # return "You don't have permission"
    print("You don't have permission")
    return redirect(url_for("accounts.login"))


app = Flask(__name__)


@login_manager.user_loader
def load_user(user_id):
    user = models.db.session.query(users.User).filter_by(id=user_id).first()
    return user


@app.route("/")
def index():
    return render_template("main/index.html")
    

if __name__ == "__main__":
    app.secret_key = "123456"  # import os // os.get_env['SECRET_KEY']
    login_manager.init_app(app)

    # app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///:memory"
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{os.getcwd()}/db/project.db"
    models.init_app(app)

    app.register_blueprint(accounts.bp)
    app.register_blueprint(folios.bp)

    app.run(debug=True)

web/views/accounts.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, login_user, logout_user

from werkzeug.security import generate_password_hash, check_password_hash

from forms import accounts as accounts_form
import models
from models import users, folios

bp = Blueprint("accounts", __name__, url_prefix="/accounts")


@bp.route("/login")
def login():
    form = accounts_form.LoginForm()
    return render_template("/accounts/login.html", form=form)


@bp.route("/do-login", methods=["POST"])
def do_login():
    # email = request.form.get("email")
    # password = request.form.get("password")

    # print("-->", email, password)
    # print(request.form)

    form = accounts_form.LoginForm()

    if not form.validate_on_submit():
        return redirect(url_for("accounts.login", **form.errors))

    user = (
        models.db.session.query(users.User)
        .filter_by(
            email=form.email.data,
        )
        .first()
    )

    if not user:
        return redirect(url_for("accounts.login", message="invalid login"))

    if not check_password_hash(user.password, form.password.data):
        return redirect(url_for("accounts.login", message="invalid password"))

    login_user(user)

    return redirect(url_for("accounts.dashboard"))


@bp.route("/register", methods=["GET", "POST"])
def register():
    form = accounts_form.RegisterForm()
    if not form.validate_on_submit():
        return render_template("/accounts/register.html", form=form)

    user = users.User()
    form.populate_obj(user)

    print(form.data)
    user.password = generate_password_hash(form.password.data, method="sha256")

    # db management
    models.db.session.add(user)
    models.db.session.commit()

    return redirect(url_for("accounts.login"))


@bp.route("/logout")
def logout():
    logout_user()
    return redirect("/")


@bp.route("/dashboard")
@login_required
def dashboard():
    folio_data = models.db.session.query(folios.Folio).all()
    return render_template("/accounts/dashboard.html", folio_data=folio_data)

@bp.route("/myfolio")
@login_required
def myfolio():
    folio_data = models.db.session.query(folios.Folio).all()
    return render_template("/accounts/myfolio.html", folio_data=folio_data)

web/views/folios.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, login_user, logout_user

from werkzeug.security import generate_password_hash, check_password_hash

from forms import folios as folios_form
import models
from models import folios

bp = Blueprint("folios", __name__, url_prefix="/folios")


@bp.route("/create", methods=["GET", "POST"])
def create():
    form = folios_form.FolioForm()
    if not form.validate_on_submit():
        return render_template("/folios/create.html", form=form)

    folio = folios.Folio()
    form.populate_obj(folio)

    models.db.session.add(folio)
    models.db.session.commit()

    return redirect(url_for("accounts.dashboard"))


@bp.route("/<folio_id>/update", methods=["GET", "POST"])
def update(folio_id):
    folio = (
        models.db.session.query(folios.Folio)
        .filter_by(
            id=folio_id,
        )
        .first()
    )

    form = folios_form.FolioForm(obj=folio)
    if not form.validate_on_submit():
        return render_template("/folios/create.html", form=form)

    form.populate_obj(folio)

    # models.db.session.update(folio)
    models.db.session.commit()

    return redirect(url_for("accounts.dashboard"))


@bp.route("/<folio_id>/delete")
@login_required
def delete(folio_id):
    folio = (
        models.db.session.query(folios.Folio)
        .filter_by(
            id=folio_id,
        )
        .first()
    )

    models.db.session.delete(folio)
    models.db.session.commit()

    return redirect(url_for("accounts.dashboard"))


@bp.route("/<folio_id>")
@login_required
def view(folio_id):
    folio = (
        models.db.session.query(folios.Folio)
        .filter_by(
            id=folio_id,
        )
        .first()
    )

    return render_template("/folios/view.html", folio=folio)

web/templates/accounts/dashboard.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Dashboard Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/dashboard/">

    <link href="https://fonts.googleapis.com/css?family=Sofia" rel="stylesheet">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
     <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      html,
      body {
        height: 100%;
      }

      body {
        background-image: url("https://images.unsplash.com/photo-1528938102132-4a9276b8e320?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80");
        background-size: cover;
      }

      .table {
        background-color: rgba(255, 255, 255, 0.8);
        background-image: linear-gradient(to right, rgba(0, 0, 0, 0.1) 1px, transparent 1px), linear-gradient(to bottom, rgba(0, 0, 0, 0.1) 1px, transparent 1px);
        background-size: 25px 25px;
      }

      .table-custom {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 70px;
      }

      .h2 {
        color:rgb(255, 255, 255);
        text-shadow: 3px 3px 4px rgb(103, 103, 103);
        position: absolute;
        top: 10%;
        left: 5%;
      }

      .line {
        border-bottom: 2px solid rgb(255, 255, 255);
        box-shadow: 3px 3px 4px rgb(103, 103, 103);
        width: 90%;
        position: absolute;
        top: 16%;
        left: 5%;
      }

      @keyframes fadeIn {
        from {
          opacity: 0;
        }
        to {
          opacity: 1;
        }
      }

      .custom-fade {
        opacity: 0;
        animation: fadeIn 1s;
        animation-delay: 0.5s;
        animation-fill-mode: forwards;
      }

    </style>

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>

<body class="fade-in custom-fade">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Dashboard</a>

      <button class="navbar-toggler" 
              type="button"  
              data-bs-toggle="collapse" 
              data-bs-target="#navbarNavAltMarkup" 
              aria-controls="navbarNavAltMarkup" 
              aria-expanded="false" 
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">

          <a class="nav-link active" aria-current="page" href="{{ url_for('folios.create') }}">Create Folios</a>
          

          <a class="nav-link active" aria-current="page" href="{{ url_for('accounts.myfolio') }}">My Portfolio</a>

          <a class="nav-link" href="{{ url_for('accounts.logout') }}">Log out</a>

        </div>
      </div>

      
    </div>
  </nav>

  <div class="container">
    <h1 class="h2">Dashboard</h1>
    <div class="line-container">
      <div class="line"></div>
    </div>
  
    <table class="table table-custom">
      <table class="table table-bordered border-dark">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Biography</th>
            <th scope="col">Education</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for folio in folio_data %}
          <tr>
            <th scope="row">{{ folio.id }}</th>
            <td>{{ folio.name }}</td>
            <td>{{ folio.email }}</td>
            <td>{{ folio.biography }}</td>
            <td>{{ folio.education }}</td>
            <td>
              <a href="{{ url_for('folios.view', folio_id=folio.id) }}" class="btn btn-primary">View</a>
              <a href="{{ url_for('folios.update', folio_id=folio.id) }}" class="btn btn-warning">Edit</a>
              <a href="{{ url_for('folios.delete', folio_id=folio.id) }}" class="btn btn-danger">Delete</a>
            </td>
          </tr>
        {% endfor %}
  
        </tbody>
      </table>
    </table>
  </div>
    
</body>

<!-- <body>

  <div class="container">
    <h1 class="h2">Dashboard</h1>
    <div class="line-container">
      <div class="line"></div>
    </div>

    <table class="table table-custom">
      <table class="table table-bordered border-dark">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Biography</th>
            <th scope="col">Education</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for folio in folio_data %}
          <tr>
            <th scope="row">{{ folio.id }}</th>
            <td>{{ folio.name }}</td>
            <td>{{ folio.email }}</td>
            <td>{{ folio.biography }}</td>
            <td>{{ folio.education }}</td>
            <td>
              <a href="{{ url_for('folios.view', folio_id=folio.id) }}" class="btn btn-primary">View</a>
              <a href="{{ url_for('folios.update', folio_id=folio.id) }}" class="btn btn-warning">Edit</a>
              <a href="{{ url_for('folios.delete', folio_id=folio.id) }}" class="btn btn-danger">Delete</a>
            </td>
          </tr>
        {% endfor %}

        </tbody>
      </table>
    </table>

      </main>
    </div>
  </div>
 -->
 </body>
</html>

web/templates/accounts/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>&#x2712; Register</title>
    <link href="https://fonts.googleapis.com/css?family=Sofia" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </head>
<style>
html,
body {
  height: 100%;
}

body {
  display: flex;
  align-items: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-image: url("https://lh3.googleusercontent.com/XxANzKGuZ4m1-h3QtAJcGXOACSOJcKR9pBVRS_S78eZjizMPp2W-UJGczMAZDoVsfdsDNZIN66vx5_UyAtv0BAhqCvWtImeqMKBoFH3erw6xc1nc72KcPdMUh3jk8eVcRr3lFOh6=w2400");
  background-size: cover;
  backdrop-filter: blur(5px);
}


.form-signin {
  max-width: 330px;
  padding: 15px;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

.custom-btn-register {
  padding: 5px 15px;
  background-color: rgb(255, 255, 255, 0);
  color: rgb(255, 255, 255);
  border-color: rgb(255, 255, 255);
  position: absolute;
  top: 74%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.custom-btn-register:hover {
  background-color: rgb(236, 135, 214, 0.85);
  border-color: rgb(236, 135, 214);
  color: rgb(255, 255, 255);
  font-weight: bold;
}

.custom-btn-summit {
  padding: 5px 120px;
  background-color: rgb(236, 135, 214, 0.85);
  color: rgb(255, 255, 255);
  border-color: rgb(236, 135, 214);
  position: absolute;
  top: 60%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.custom-btn-summit:hover {
  background-color: rgb(255, 255, 255, 0);
  border-color: rgb(255, 255, 255);
  color: rgb(255, 255, 255);
  font-weight: bold;
}

.mb-4 {
  position: absolute;
  top: 20%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.h3 {
  color: rgb(255, 255, 255);
  font-size: 3em;
  text-shadow: 3px 3px 4px #ddb8e6;
  font-weight: bold;
  position: absolute;
  top: 20%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-family: "Sofia", sans-serif;
}

.form-floating {
  opacity: 0.8;
  position: relative;
  top: 30%;
  left: 0%;
  transform: translateY(-60px);
}

.checkbox {
  color: rgb(255, 255, 255);
  position: absolute;
  top: 52%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.line-container {
  color: rgb(255, 255, 255);
  display: flex;
  align-items: center;
  position: relative;
  left: 0%;
  transform: translateY(65px);
}
.line {
  border-bottom: 2px solid rgb(255, 255, 255);
  width: 50%;
}
.or {
  width: 25%;
  text-align: center;
}

.alert-danger {
  padding: 5px 15px;
  position: absolute;
  top: 82%;
  left: 50%;
  transform: translate(-50%, -50%);
}

@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

.custom-fade {
  opacity: 0;
  animation: fadeIn 1s;
  animation-delay: 0.3s;
  animation-fill-mode: forwards;
}

</style>


  <body class="fade-in custom-fade">
    <div class="container">
      <div class="text-center">
        <main class="form-signin w-100 m-auto">
          <form action="{{ url_for('accounts.do_login') }}" method="POST">

            {{ form.hidden_tag() }}
            
              <h1 class="h3 mb-3 fw-normal">Welcome to Portfolio</h1>

              <div class="form-floating">
                <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
                <label for="floatingInput">Email address</label>
              </div>

              <div class="form-floating">
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                <label for="floatingPassword">Password</label>
              </div>

              <div class="checkbox mb-3">
                <label>
                  <input type="checkbox" value="remember-me"> Remember me
                </label>
              </div>

            <button class="btn btn-light btn-lg custom-btn-summit" type="submit">Sign in</button>

            <div class="line-container">
              <div class="line"></div>
              <div class="or">Or</div>
              <div class="line"></div>
            </div>
        
            <a class="btn btn-light btn-lg custom-btn-register" href="{{ url_for('accounts.register') }}">Create Account</a>

          </form>
          
          {% if request.args | length > 0 %}

            <div  class="alert alert-danger" role="alert">
              <ul>
              {% for k, v in request.args.items() %}
                <li><b>{{ k }}: </b> {{ v }}</li>
              {% endfor %}
              </ul>
            </div>

          {% endif %}
        
        </main>  
      </div>
    </div>
  </body>
</html>

web/templates/base/nav.html
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('accounts.dashboard') }}">
              <span data-feather="home" class="align-text-bottom"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('folios.create') }}">
              <span data-feather="file" class="align-text-bottom"></span>
              Create Folios
            </a>
          </li>
         </ul>
      </div>
    </nav>

web/templates/folios/view.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Dashboard Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/dashboard/">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
     <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      body {
        background-image: url("https://lh3.googleusercontent.com/Zsc8mV3K1shc66Evk1gK3mPJ7tf-mN5qUyB984-_olCz959gudvLcx6rWL-z2B_cH55BsU9Rq1iiNalMp2GcHZOQbHhN810dsWKUCxQqXbdSMO2eny4C604iq9EPoS3MyCADQxvTOQ=w2400");
        background-size: cover;
      }

      .h2 {
        color:rgb(255, 255, 255);
        position: absolute;
        top: 10%;
        left: 5%;
      }

      .line {
        border-bottom: 2px solid rgb(255, 255, 255);
        width: 90%;
        position: absolute;
        top: 16%;
        left: 5%;
      }

      .card {
        width: 50%;
        position: absolute;
        top: 35%;
        left: 25%;
        background-color: rgba(255, 255, 255, 0.8);
      }

      .custom-btn-dashboard {
        background-color: rgb(236, 135, 214, 0.85);
        border-color: rgb(236, 135, 214);
        color: rgb(255, 255, 255);
      }

      .custom-btn-dashboard:hover {
        padding: 5px 15px;
        background-color: rgb(255, 255, 255, 0);
        color: rgb(255, 255, 255);
        border-color: rgb(255, 255, 255);
        font-weight: bold;
      }

      @keyframes fadeIn {
        from {
          opacity: 0;
        }
        to {
          opacity: 1;
        }
      }

      .custom-fade {
        opacity: 0;
        animation: fadeIn 1s;
        animation-delay: 0.5s;
        animation-fill-mode: forwards;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>

<body class="fade-in custom-fade">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('accounts.dashboard') }}">Dashboard</a>

      <button class="navbar-toggler" 
              type="button"  
              data-bs-toggle="collapse" 
              data-bs-target="#navbarNavAltMarkup" 
              aria-controls="navbarNavAltMarkup" 
              aria-expanded="false" 
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">

          <a class="nav-link active" aria-current="page" href="{{ url_for('folios.create') }}">Create Folios</a>
          

          <a class="nav-link" href="#">My Port Folio</a>

          <a class="nav-link" href="{{ url_for('accounts.logout') }}">Log out</a>

        </div>
      </div>

      
    </div>
  </nav>

  <div class="container-fluid">
    <h1 class="h2">Dashboard</h1>
    <div class="line-container">
      <div class="line"></div>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      {{ folio.name }}
    </div>
    <div class="card-body">
      <p class="card-text">Email : {{ folio.email }}</p>
      <p class="card-text">Biography : {{ folio.biography }}</p>
      <p class="card-text">Education : {{ folio.education }}</p>
      <a href="{{ url_for('accounts.dashboard') }}" class="btn btn-outline-light custom-btn-dashboard">Back</a>
    </div>
  </div>
    
</body>

 </body>
</html>